### ISSUE TITLE
CSS/JS Injector shows error but works

### ISSUE THREAD

**Issue by JouanDeag** [wisp-gg/frontend#47]
**Describe the bug**
When using the css injector it shows an error when saving and clears the input but changes still gets made and shows.

**To Reproduce**
1. Go to Admin -> Administration -> CSS Injector
2.. Write CSS
3. Click Save

**Expected behavior**
I expect to not see an error and see my CSS Code in the editor inside the panel.

**Screenshots**
![image](https://user-images.githubusercontent.com/61161558/153763119-7c709dd7-d8ca-4baa-a417-7befcb1a1e17.png)

Desktop (please complete the following information):
OS: Windows 10
Browser: Chrome
Version: 98.0.4758.82

**Comment by TrixterTheTux** [comment]
Should be fixed in the next release.

**Comment by JouanDeag** [comment]
![image](https://user-images.githubusercontent.com/61161558/154816178-dfbabfc0-cf82-4e5e-8ae2-730ca8c0dc5a.png)
![image](https://user-images.githubusercontent.com/61161558/154816197-2a793aa0-bcd3-431b-89f7-48aed19432c8.png)
![image](https://user-images.githubusercontent.com/61161558/154816206-d11a4405-e321-4283-9a98-2552f8b918f2.png)

Still an issue

**Comment by TrixterTheTux** [comment]
Should be fixed by https://github.com/wisp-gg/frontend/commit/820237a78d7d6259a9c6288f023d3d317ed30900, though leaving this open until I can confirm this fix works in production.
